import type { Metadata } from "next";
import { Footer, NavBar } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <>
          <div className="flex flex-col min-h-screen">
            <NavBar />
            <div className="pt-20 flex-grow">{children}</div>
            <Footer />
          </div>
        </>
      </body>
    </html>
  );
}
